apiVersion: v1
kind: Secret
metadata:
  name: projectsync-secrets
type: Opaque
stringData:
  mongo-uri: "mongodb+srv://flyingsakura4_db_user:JL5s0Szt6ITH03EM@cluster0.8d11uqg.mongodb.net/merncap?appName=Cluster0"
  jwt-secret: "supersecretjwtkey"